name: main.yml

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #6.01.1

      - name: Setup Java 21
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e #5.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven # GitHub caches in .m2 folder

      - name: Kompiler kode
        run: mvn clean compile

  test:
    runs-on: ubuntu-latest
    needs: build # Skaber afhængighed mellem jobs
    steps:
      - name: Checkout kode
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #6.01.1

      - name: Setup Java 21
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e #5.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Kør unit tests
        run: mvn test
